server:
  port: 8082
spring:

  dubbo:
    application: item-web
    registry:
      address: 192.168.40.128:2181
      protocol: zookeeper
    protocol:
      name: dubbo
    base-package: com.atgui.gmall
    consumer:
      timeout: 60000
      check: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
